### ISSUE TITLE
2019 Compatibility

### ISSUE THREAD

**Issue by Aoost** [keijiro/RDSystem#1]
Hi Keijiro, I was wondering what approach you would take to building Reaction Diffusion Displacement in Unity 2019 would be given the shadergraph implementation, your project sadly doesn't work in Unity 2019.1 or 2019.2 and I haven't found much in the way of resources describing the new Render Texture workflow in the HD and LW Renderpipelines?

**Comment by keijiro** [comment]
- The compatibility problem is in the post processing stack. This project gets to work on Unity 2019.2 by removing `Asset/PostProcessing`.
- You can use the custom render texture on HD/LW RP in the same way as before. You can use it without any change.
- Unfortunately Shader Graph doesn't support custom render textures. So, there is nothing new here. Please keep using the old shaders.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further problems.

**Comment by Aoost** [comment]
Hi,

I'm getting a TextMesh Pro error that seems to be problematic for a number
of users in the new unity. Will see if I can resolve.
